ARCHS = armv7 armv7s arm64
include theos/makefiles/common.mk

TOOL_NAME = fsmonitord
fsmonitord_FILES = main.m
fsmonitord_LIBRARIES = rocketbootstrap
fsmonitord_PRIVATE_FRAMEWORKS = AppSupport
fsmonitord_INSTALL_PATH = /usr/libexec

include $(THEOS_MAKE_PATH)/tool.mk
