#!/bin/sh
chown root /Library/LaunchDaemons/com.eswick.fsmonitord.plist
chmod 644 /Library/LaunchDaemons/com.eswick.fsmonitord.plist

if [[ $1 == remove || $1 == purge ]]; then
    launchctl unload /Library/LaunchDaemons/com.eswick.fsmonitord.plist
fi

exit 0